version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fashion_shop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - fashion_shop_network

  db:
    image: mysql:8.0
    container_name: fashion_shop_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fashion_shop_network

  nginx:
    image: nginx:alpine
    container_name: fashion_shop_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fashion_shop_network

networks:
  fashion_shop_network:
    driver: bridge

volumes:
  dbdata:
